// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetWeb.Data;

#nullable disable

namespace ProjetWeb.Migrations
{
    [DbContext(typeof(ProjetWebContext))]
    [Migration("20231214000330_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("ProjetWeb.Models.Evenement", b =>
                {
                    b.Property<int>("EvenementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureRevisee")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDVol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .HasColumnType("TEXT");

                    b.HasKey("EvenementID");

                    b.ToTable("Evenement");
                });

            modelBuilder.Entity("ProjetWeb.Models.Vol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeVol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compagnie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeurePrevue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeureRevisee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vol");
                });
#pragma warning restore 612, 618
        }
    }
}
