// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetWeb.Data;

#nullable disable

namespace ProjetWeb.Migrations
{
    [DbContext(typeof(ProjetWebContext))]
    partial class ProjetWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ProjetWeb.Models.Evenement", b =>
                {
                    b.Property<int>("EvenementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureRevisee")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDVol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .HasColumnType("TEXT");

                    b.HasKey("EvenementID");

                    b.HasIndex("IDVol");

                    b.ToTable("Evenement");
                });

            modelBuilder.Entity("ProjetWeb.Models.Vol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeVol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compagnie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeurePrevue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeureRevisee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vol");
                });

            modelBuilder.Entity("ProjetWeb.Models.Evenement", b =>
                {
                    b.HasOne("ProjetWeb.Models.Vol", "Vol")
                        .WithMany("Evenements")
                        .HasForeignKey("IDVol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("ProjetWeb.Models.Vol", b =>
                {
                    b.Navigation("Evenements");
                });
#pragma warning restore 612, 618
        }
    }
}
